# -*- coding: utf-8 -*-
"""
Reels/qisqa video ssenariylari bazasi.
Har biri: hook (birinchi 2 soniyada aytiladigan gap), tuzilma (nima ko'rsatish/aytish kerak),
va cta (video oxirida chaqiruv). Foydalanuvchi shaxsiy brendiga moslab o'zgartirishi mumkin.
"""

SCENARIOS = [
    {"title": "Kun boshlanishi (GRWM uslubida)",
     "hook": "Mana mening [challenge/ish]ga tayyorlanish jarayonim",
     "body": "Ertalabki tayyorgarlik yoki ish joyingizga kelish jarayonini tezlashtirilgan videoda ko'rsating",
     "cta": "Sizning kuningiz qanday boshlanadi? Komentda yozing"},
    {"title": "Oldin / Keyin",
     "hook": "1-kunda men bunday edim, hozir esa...",
     "body": "Challenge yoki loyihangiz boshlanishidagi va hozirgi holatingizni yonma-yon solishtiring",
     "cta": "Sizda ham shunday o'zgarish bo'lganmi?"},
    {"title": "3 ta keng tarqalgan xato",
     "hook": "Sohamda odamlar shu 3 xatoni doim qiladi",
     "body": "Sohangizdagi 3 ta tez-tez uchraydigan xatoni sanab, har biriga qisqa izoh bering",
     "cta": "Qaysi birini o'zingizda ko'rgansiz?"},
    {"title": "Savol-javob",
     "hook": "Menga eng ko'p beriladigan savol shu edi...",
     "body": "Obunachilardan kelgan (yoki tez-tez so'raladigan) bitta savolga to'liq javob bering",
     "cta": "Savolingiz bo'lsa, komentga yozing — keyingi videoda javob beraman"},
    {"title": "Mif va haqiqat",
     "hook": "Hammaning sizga aytmagan haqiqati bor",
     "body": "Sohangizdagi keng tarqalgan noto'g'ri fikrni ayting, keyin haqiqatini tushuntiring",
     "cta": "Bu sizga yangilik bo'ldimi?"},
    {"title": "60 soniyalik amaliy maslahat",
     "hook": "Buni bugundan boshlab qo'llang",
     "body": "Darhol amalga oshirsa bo'ladigan bitta konkret maslahat bering, misol bilan",
     "cta": "Sinab ko'ring va natijani yozing"},
    {"title": "Nega men buni boshladim",
     "hook": "Hammasi shu voqeadan boshlangan edi...",
     "body": "Shaxsiy brend yoki challengeni boshlashga turtki bo'lgan voqeani hikoya qiling",
     "cta": "Sizni nima harakatga keltirdi?"},
    {"title": "Kulisa (Behind the scenes)",
     "hook": "Bu postning orqasida nima bor, ko'rsataman",
     "body": "Kontent tayyorlash yoki ish jarayonining ko'rinmas qismini ko'rsating",
     "cta": "Bunday videolarni ko'proq xohlaysizmi?"},
    {"title": "Bugungi progress",
     "hook": "Challengening [X]-kuni, ana natija",
     "body": "Bugungi kichik yutuq yoki o'zgarishni ko'rsating, raqam yoki holat bilan",
     "cta": "Meni kuzatib boring, ertaga davomi bor"},
    {"title": "Top-3 tavsiya",
     "hook": "Shu 3 tasi hayotimni osonlashtirdi",
     "body": "Sohangizga oid 3 ta ilova, kitob yoki vositani sanab, qisqa izoh bering",
     "cta": "Sizniki qaysi? Yozing"},
    {"title": "Trendga reaksiya",
     "hook": "Bu trend haqida fikrim shunday",
     "body": "Hozirgi mashhur trend yoki mavzuga o'z sohangiz nuqtai nazaridan sharh bering",
     "cta": "Siz nima deb o'ylaysiz?"},
    {"title": "Fikr-mulohaza ekranga",
     "hook": "Bir obunachim menga shunday yozdi",
     "body": "Kimningdir xabarini yoki fikrini ekranga chiqarib, unga munosabat bildiring",
     "cta": "Sizda ham shunday tajriba bo'lganmi?"},
    {"title": "Men vs ko'pchilik",
     "hook": "Ko'pchilik shunday qiladi, men esa boshqacha",
     "body": "O'zingizning noodatiy yondashuvingizni odatiy usul bilan solishtiring",
     "cta": "Qaysi usul sizga yoqadi?"},
    {"title": "Jonli tajriba",
     "hook": "Keling, buni birga sinab ko'ramiz",
     "body": "Biror usul yoki vositani jonli tarzda sinab, natijani ko'rsating",
     "cta": "Natija qanday bo'lishini taxmin qiling"},
    {"title": "Challenge yangiligi",
     "hook": "Bugun challengeda muhim narsa o'rgandim",
     "body": "Challenge davomida qo'lga kiritgan yangi bilim yoki tajribani ulashing",
     "cta": "Siz ham shunday challenge qilyapsizmi?"},
    {"title": "Kun tartibim",
     "hook": "Mana mening bir kunlik tartibim",
     "body": "Kuningizning asosiy qismlarini tezlashtirilgan formatda ko'rsating",
     "cta": "O'zingiznikini ham ulashing"},
    {"title": "1 daqiqada dars",
     "hook": "Buni tushunish uchun 1 daqiqa yetarli",
     "body": "Murakkab tushunchani sodda tilda, misol bilan tushuntiring",
     "cta": "Tushunarli bo'ldimi? Yozing"},
    {"title": "Muvaffaqiyatsizlik hikoyasi",
     "hook": "Bir marta katta xato qilgandim",
     "body": "O'z xatoingiz va undan olgan saboqni ochiq gapirib bering",
     "cta": "Sizning eng katta sabog'ingiz nima edi?"},
    {"title": "5 ta belgi ro'yxati",
     "hook": "Agar shu 5 tasi sizda bo'lsa...",
     "body": "Muayyan holat yoki muammoning belgilarini ro'yxat qilib sanang",
     "cta": "Nechtasi sizga to'g'ri keldi?"},
    {"title": "Vaqt tejash hiylasi",
     "hook": "Bu hiyla menga har kuni 1 soat tejaydi",
     "body": "Ish jarayonini tezlashtiradigan amaliy hiylani ko'rsating",
     "cta": "Sinab ko'rasizmi?"},
    {"title": "Motivatsion eslatma",
     "hook": "Agar bugun charchagan bo'lsangiz, buni eshiting",
     "body": "Qisqa, samimiy motivatsion gap yoki shaxsiy tajribangizdan ilhomlantiruvchi jumla ayting",
     "cta": "Kimga kerak bo'lsa, ulashing"},
    {"title": "Ortga nazar (1-kun vs bugun)",
     "hook": "1-kuni o'zimga ishonmagandim",
     "body": "Challenge yoki loyihaning boshlanishidagi holatingiz va his-tuyg'ularingizni eslang",
     "cta": "Siz ham boshlaganingizda shunday bo'lganmisiz?"},
    {"title": "Tez-tez so'raladigan savollar",
     "hook": "Bugun 3 ta savolga javob beraman",
     "body": "Obunachilardan kelgan 3 ta qisqa savolga ketma-ket javob bering",
     "cta": "Yana savol bo'lsa, yozavering"},
    {"title": "Vosita/ilova sharhi",
     "hook": "Bu ilova ishimni butunlay osonlashtirdi",
     "body": "Foydali bitta vosita yoki ilovani ko'rsatib, qanday ishlatishni tushuntiring",
     "cta": "Sizda qanday sevimli vositalar bor?"},
    {"title": "Kichik yutuq e'loni",
     "hook": "Buni sizlar bilan bo'lishmasdan bo'lmaydi",
     "body": "Kichik ham bo'lsa, so'nggi yutuq yoki natijani hayajon bilan e'lon qiling",
     "cta": "Rahmat qo'llab-quvvatlaganlarga!"},
    {"title": "Ha/Yo'q so'rovnoma uslubi",
     "hook": "Sizningcha, shu to'g'rimi yoki noto'g'ri?",
     "body": "Sohangizdagi bahsli fikrni aytib, tomoshabinni fikr bildirishga undang",
     "cta": "Izohda ha yoki yo'q deb yozing"},
    {"title": "Qadam-baqadam ko'rsatma",
     "hook": "Buni 3 qadamda bajarish mumkin",
     "body": "Biror ishni 3 aniq qadamga bo'lib, har birini qisqa ko'rsating",
     "cta": "Saqlab qo'ying, kerak bo'ladi"},
    {"title": "Shaxsiy qadriyat",
     "hook": "Men bunga qattiq ishonaman",
     "body": "Ishingiz yoki hayotingizdagi asosiy qadriyat yoki tamoyilni his-tuyg'u bilan ayting",
     "cta": "Siz nimaga ishonasiz?"},
    {"title": "Tezkor taqqoslash",
     "hook": "A yaxshimi yoki B? Keling ko'ramiz",
     "body": "Ikki variant, usul yoki mahsulotni tez va aniq taqqoslang",
     "cta": "Siz qaysi birini tanlagan bo'lardingiz?"},
    {"title": "Kundalik izoh (vlog uslubi)",
     "hook": "Bugun shunday kun bo'ldi...",
     "body": "Kuningizdagi qiziq yoki muhim voqeani erkin, samimiy uslubda hikoya qiling",
     "cta": "Sizning kuningiz qanday o'tdi?"},
    {"title": "Ekspert maslahati",
     "hook": "Mutaxassis sifatida shuni aytaman",
     "body": "Sohangiz bo'yicha chuqurroq, professional maslahat bering",
     "cta": "Bu foydali bo'ldimi?"},
    {"title": "Challenge qiyinchiligi",
     "hook": "Bu kun eng qiyin kunlardan biri bo'ldi",
     "body": "Challenge davomidagi qiyinchilikni ochiq gapirib, qanday yengganingizni ayting",
     "cta": "Siz qanday qiyinchiliklarni yengib o'tgansiz?"},
    {"title": "3 daqiqada natija",
     "hook": "Bu usulni ishlatgach, natija tez keldi",
     "body": "Qisqa muddatda ko'zga ko'ringan natijani misol bilan ko'rsating",
     "cta": "Siz ham sinab ko'rasizmi?"},
    {"title": "Sabab-natija hikoyasi",
     "hook": "Agar shuni qilmaganimda, bunday bo'lmasdi",
     "body": "Bitta qaror qanday natijaga olib kelganini hikoya tarzida tushuntiring",
     "cta": "Sizda ham shunga o'xshash tajriba bormi?"},
    {"title": "Odatiy kun ichida fokus lahzasi",
     "hook": "Mana men eng ko'p fokuslanadigan payt",
     "body": "Kuningizdagi eng samarali yoki muhim daqiqani ko'rsating",
     "cta": "Sizning eng samarali vaqtingiz qachon?"},
    {"title": "Obunachi yutug'i",
     "hook": "Bir obunachim ajoyib natijaga erishdi",
     "body": "Kimningdir (ruxsati bilan) yutug'ini misol qilib ko'rsating va tabriklang",
     "cta": "Keyingi muvaffaqiyat sizniki bo'lishi mumkin"},
    {"title": "Tezkor tekshiruv-ro'yxat",
     "hook": "Boshlashdan oldin shu ro'yxatni tekshiring",
     "body": "Biror ishni boshlashdan oldin kerak bo'ladigan narsalarni ro'yxat qilib bering",
     "cta": "Saqlab qo'ying, keyin kerak bo'ladi"},
    {"title": "Shaxsiy sabr hikoyasi",
     "hook": "Bunga qancha vaqt ketganini bilsangiz...",
     "body": "Natijaga erishish uchun ketgan vaqt va sabr haqida ochiq gapiring",
     "cta": "Sabr qilish qiyinmi sizga ham?"},
    {"title": "Tez-tez ishlatiladigan iboralar",
     "hook": "Sohamda bu so'zlar nimani anglatadi",
     "body": "Sohangizga xos 2-3 ta atama yoki iborani sodda tilda tushuntiring",
     "cta": "Boshqa qaysi atamalarni bilmoqchisiz?"},
    {"title": "Kunlik yakun (recap)",
     "hook": "Bugungi kunni shu bilan yakunlayman",
     "body": "Kun davomida qilgan ishlar yoki o'rgangan narsalarni qisqa sanab bering",
     "cta": "Ertaga yana ko'rishguncha!"},
]
